<?php

declare(strict_types=1);

namespace Vatsake\SmartIdV3\Enums;

enum SessionEndResult: string
{
    case OK = 'OK';
    case USER_REFUSED = 'USER_REFUSED';
    case TIMEOUT = 'TIMEOUT';
    case DOCUMENT_UNUSABLE = 'DOCUMENT_UNUSABLE';
    case WRONG_VC = 'WRONG_VC';
    case REQUIRED_INTERACTION_NOT_SUPPORTED_BY_APP = 'REQUIRED_INTERACTION_NOT_SUPPORTED_BY_APP';
    case USER_REFUSED_CERT_CHOICE = 'USER_REFUSED_CERT_CHOICE';
    case USER_REFUSED_INTERACTION = 'USER_REFUSED_INTERACTION';
    case PROTOCOL_FAILURE = 'PROTOCOL_FAILURE';
    case EXPECTED_LINKED_SESSION = 'EXPECTED_LINKED_SESSION';
    case SERVER_ERROR = 'SERVER_ERROR';
}
